// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfxxinrrxhwxtgfttqfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmeHhpbnJyeGh3eHRnZnR0cWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODUwNzEsImV4cCI6MjA1ODQ2MTA3MX0.IFRTWd6QKw5dRyZ968r4pAUusWdecwlx25iGuCfCod4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);